"""empty message.

Revision ID: 5eaa1cb609e5
Revises:
Create Date: 2024-06-14 22:11:48.587424
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5eaa1cb609e5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "author",
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("author_id"),
    )
    op.create_table(
        "book",
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["author.author_id"],
        ),
        sa.PrimaryKeyConstraint("book_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("book")
    op.drop_table("author")
    # ### end Alembic commands ###
